# Create a new config map for every Deployment.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-topo-configmap
data:
  {{- range $path, $_ :=  .Files.Glob  "scenarios/**.yaml" }}    
  {{ $path | trimPrefix "scenarios/" }}: |- 
{{ $.Files.Get $path | indent 4 }}
  {{ end }}

